KaryaManager/KaryaManager/KaryaManager/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contact_id { get; set; }
        public int primary_userId { get; set; }
        public int secondary_userId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}

KaryaManager/KaryaManager/KaryaManager/Controllers/ContactController.cs
using KaryaManager.DAL;
using KaryaManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KaryaManager.CustomWebSecurityWrapper;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace KaryaManager.Controllers
{
    public class ContactController : Controller
    {
        private UnitOfWork unitOfWork;
        private WebSecurityWrapper webSecurity;

        public ContactController()
        {
            unitOfWork = new UnitOfWork();
            webSecurity = new WebSecurityWrapper();
        }

        public ContactController(UnitOfWork uw = null, WebSecurityWrapper wr = null)
        {
            if (uw == null)
                unitOfWork = new UnitOfWork();
            else
                unitOfWork = uw;
            if(wr == null)
                webSecurity = new WebSecurityWrapper();
            else
                this.webSecurity = wr;
        }


        //
        // GET: /Contact/

        public ActionResult Index()
        {
            User user = unitOfWork.UserRepository.GetByID(webSecurity.CurrentUserId);
            return View(user.Contacts);
        }

        public ActionResult Create()
        {
            // Get ALL user except the current user
            IEnumerable<User> users = unitOfWork.UserRepository.Get();
            users = users.Where(usr => usr.userId != webSecurity.CurrentUserId);

            // Get all contact belongs to the current user
            IEnumerable<Contact> contacts = unitOfWork.ContactRepository.Get();
            contacts = contacts.Where(usr => usr.primary_userId == webSecurity.CurrentUserId);

            // Filter user to get the user who are Not in the current user contact list
            users = users.Where(usr => !isUserInContact(usr.userId, contacts));
            ViewBag.secondary_user = new SelectList(users, "userId", "userName");
            return PartialView(new Contact());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contact contact)
        {

            if (ModelState.IsValid)
            {
                contact.primary_userId = webSecurity.CurrentUserId;
                unitOfWork.ContactRepository.Insert(contact);
                unitOfWork.Commit();
                TempData["message"] = "Contact added successfully.";
                return RedirectToAction("Index", "Workspace");
                // return RedirectToAction("Index");

            }
            return PartialView(contact);
        }

        public ActionResult Delete(int id = 0)
        {
            if (!unitOfWork.ContactRepository.Delete(id))
            {
                return HttpNotFound();
            }
            unitOfWork.Commit();
            TempData["message"] = "Contact deleted successfully.";
            return RedirectToAction("Index");
        }

        [NonAction]
        public Boolean isUserInContact(int userId, IEnumerable<Contact> contacts)
        {
            foreach (Contact contact in contacts)
            {
                if (contact.secondary_userId == userId)
                    return true;
            }
            return false;
        }

    }
}

KaryaManager/KaryaManager/KaryaManager/Views/Contact/Create.cshtml
@model KaryaManager.Models.Contact

@{
    ViewBag.Title = "Add";
}

@*<h2>Create</h2>*@

@using (Html.BeginForm("Create", "Contact", FormMethod.Post, new { id = "createContactForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Contact</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.secondary_userId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.secondary_userId, (SelectList)ViewBag.secondary_user, String.Empty)
            @Html.ValidationMessageFor(model => model.secondary_userId)
        </div>
        <p>
            <input type="submit" class="btn btn-primary" value="Add Contact" />
        </p>
    </fieldset>
}

@*<div>
    @Html.ActionLink("Back", "Index", "Workspace")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KaryaManager/KaryaManager/KaryaManager/Views/Contact/Index.cshtml
@model IEnumerable<KaryaManager.Models.Contact>
@{
    ViewBag.Title = "Project";
}

<h2>Project</h2>
<div class="display-field">
    <table  class="table table-striped">
        <tr>
            <th>User Name</th>
            <th>Email</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User1.userName) 
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User1.Email) 
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id=item.contact_id })
                </td>
            </tr>
        }
    </table>
</div>
<div>
    @Html.ActionLink("Back", "Index", "Workspace")
</div>