KaryaManager/KaryaManager/KaryaManager/Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Project_user = new HashSet<Project_user>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int projectId { get; set; }
        public int ownerId { get; set; }
        public string projectName { get; set; }
        public string projectStatus { get; set; }
        public string projectDescription { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Project_user> Project_user { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}

KaryaManager/KaryaManager/KaryaManager/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KaryaManager.Models;
using KaryaManager.DAL;
using WebMatrix.WebData;
using System.Web.Security;
using KaryaManager.CustomWebSecurityWrapper;

namespace KaryaManager.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private UnitOfWork unitOfWork;
        private WebSecurityWrapper webSecurity;

        public ProjectController()
        {
            unitOfWork = new UnitOfWork();
            webSecurity = new WebSecurityWrapper();
        }

        public ProjectController(UnitOfWork uw = null, WebSecurityWrapper wr = null)
        {
            if (uw == null)
                unitOfWork = new UnitOfWork();
            else
                unitOfWork = uw;
            if(wr == null)
                webSecurity = new WebSecurityWrapper();
            else
                this.webSecurity = wr;
        }

        //
        // GET: /Project/

        public ActionResult Index()
        {
            //var projects = db.Projects.Include(p => p.User);
            var projects = unitOfWork.ProjectRepository.Get();
            return View(projects);
        }

        //
        // GET: /Project/Details/5

        public ActionResult Details(int id = 0)
        {
            Project project = unitOfWork.ProjectRepository.GetByID(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        //
        // GET: /Project/Create
        public ActionResult Create()
        {
            Project project = new Project();
            ViewBag.project_statuses = getProjectStatuses();
            return PartialView(project);
        }

        //
        // POST: /Project/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project project)
        {
            
            if (ModelState.IsValid)
            {
                project.ownerId = webSecurity.CurrentUserId;
                project.projectStatus = "Open";
                unitOfWork.ProjectRepository.Insert(project);
                unitOfWork.Commit();
                establishProjectRole(project.projectId);
                TempData["message"] = "Project created successfully.";
                return RedirectToAction("Index", "Workspace");
               // return RedirectToAction("Index");
                
            }
            ViewBag.project_statuses = new SelectList(getProjectStatuses());
            return PartialView(project);
            //ViewBag.ownerId = new SelectList(db.Users, "userId", "userName", project.ownerId);
            //return View(project);
        }

        //
        // GET: /Project/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole)))
                return HttpNotFound();
            Project project = unitOfWork.ProjectRepository.GetByID(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.project_statuses = getProjectStatuses();
           // ViewBag.ownerId = new SelectList(db.Users, "userId", "userName", project.ownerId);
            return PartialView(project);
        }

        //
        // POST: /Project/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.ProjectRepository.Update(project);
                unitOfWork.Commit();
                //db.Entry(project).State = EntityState.Modified;
                //db.SaveChanges();
                TempData["message"] = "Project updated successfully.";
                return RedirectToAction("Index", "Dashboard", new { id = project.projectId } );
            }
            ViewBag.project_statuses = getProjectStatuses();
            //ViewBag.ownerId = new SelectList(db.Users, "userId", "userName", project.ownerId);
            return PartialView(project);
        }

        public ActionResult DeletePrompt(int id)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole)))
                return HttpNotFound();
            try
            {
                unitOfWork.ProjectRepository.Delete(id);
                unitOfWork.Commit();
                deleteProjectRole(id);
                TempData["message"] = "Project deleted successfully.";
                return RedirectToAction("Index", "Workspace");
            }
            catch
            {
                TempData["error"] = "Error deleting task.";
                return RedirectToAction("Index", "Workspace");
            }
        }

        //
        // GET: /Project/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole)))
                return HttpNotFound();
            if(!unitOfWork.ProjectRepository.Delete(id))
            {
                return HttpNotFound();
            }
            deleteProjectRole(id);
            unitOfWork.Commit();
            TempData["message"] = "Project deleted successfully.";
            return RedirectToAction("Index", "Workspace");
        }

        protected override void Dispose(bool disposing)
        {
            unitOfWork.Dispose();
            base.Dispose(disposing);
        }

        [NonAction]
        public List<String> getProjectStatuses ()
        {
            List<String> ret = new List<String>();
            foreach(ProjectStatus status in Enum.GetValues(typeof(ProjectStatus)))
                ret.Add(EnumExtension.GetEnumDescription(status));
            return ret;
        }

        [NonAction]
        public void establishProjectRole(int projectId)
        {
            String leaderRole = projectId + " Leader";
            String memberRole = projectId + " Member";
            Roles.CreateRole(leaderRole);
            Roles.CreateRole(memberRole);
            Roles.AddUserToRole(webSecurity.CurrentUserName, leaderRole);
        }

        [NonAction]
        public void deleteProjectRole(int projectId)
        {
            String leaderRole = projectId + " Leader";
            String memberRole = projectId + " Member";
            Roles.RemoveUsersFromRole(Roles.GetUsersInRole(leaderRole), leaderRole);
            Roles.DeleteRole(leaderRole);
            string[] members = Roles.GetUsersInRole(memberRole);
            if (members.Length >= 1)
                Roles.RemoveUsersFromRole(members, memberRole);
            Roles.DeleteRole(memberRole);
        }
    }
}

KaryaManager/KaryaManager/KaryaManager/Views/Project/Create.cshtml
@model KaryaManager.Models.Project

@{
    ViewBag.Title = "Create";
}

@*<h2>Create</h2>*@

@using (Html.BeginForm("Create", "Project", FormMethod.Post, new { id = "createProjectForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project</legend>

        @Html.HiddenFor(model => model.projectId)
        @Html.HiddenFor(model => model.ownerId)
        @Html.HiddenFor(model => model.projectStatus)


        <div class="editor-label">
            @Html.LabelFor(model => model.projectName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.projectName,  new { placeholder = "Name" } )
            @Html.ValidationMessageFor(model => model.projectName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.projectDescription)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.projectDescription, new { placeholder = "Descriptions" })
            @Html.ValidationMessageFor(model => model.projectDescription)
        </div>

        <p>
            <input type="submit" class="btn btn-primary" value="Create" />
        </p>
    </fieldset>
}

@*<div>
    @Html.ActionLink("Back", "Index", "Workspace")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KaryaManager/KaryaManager/KaryaManager/Views/Project/Delete.cshtml
@model KaryaManager.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Project</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.userName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.userName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.projectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.projectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.projectStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.projectStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.projectDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.projectDescription)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

KaryaManager/KaryaManager/KaryaManager/Views/Project/Details.cshtml
@model KaryaManager.Models.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Project</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.userName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.userName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.projectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.projectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.projectStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.projectStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.projectDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.projectDescription)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.projectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KaryaManager/KaryaManager/KaryaManager/Views/Project/Edit.cshtml
@model KaryaManager.Models.Project

@{
    ViewBag.Title = "Edit";
}

@*<h2>Edit</h2>*@

@using (Html.BeginForm("Edit", "Project", FormMethod.Post, new { id = "editProjectForm" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project</legend>

 
        @Html.HiddenFor(model => model.projectId)
        @Html.HiddenFor(model => model.ownerId)

        
        <div class="editor-label">
            @Html.LabelFor(model => model.projectName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.projectName)
            @Html.ValidationMessageFor(model => model.projectName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.projectDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.projectDescription)
            @Html.ValidationMessageFor(model => model.projectDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.projectStatus)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.projectStatus, new SelectList(ViewBag.project_statuses))
            @Html.ValidationMessageFor(model => model.projectStatus)
        </div>

        <p>
            <input type="submit" class="btn btn-primary" value="Save" />
        </p>
    </fieldset>
}

@*<div>
    @Html.ActionLink("Back", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KaryaManager/KaryaManager/KaryaManager/Views/Project/Index.cshtml
@model IEnumerable<KaryaManager.Models.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.projectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.projectStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.projectDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.projectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.projectStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.projectDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.projectId }) |
            @Html.ActionLink("Details", "Details", new { id=item.projectId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.projectId })
        </td>
    </tr>
}

</table>