KaryaManager/KaryaManager/KaryaManager/Models/Task.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskId { get; set; }
        public string taskName { get; set; }
        public string taskStatus { get; set; }
        public string taskDescription { get; set; }
        public Nullable<int> assignee { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<int> estimate_hour { get; set; }
        public Nullable<int> worked_hour { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<int> projectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}

KaryaManager/KaryaManager/KaryaManager/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KaryaManager.Models;
using KaryaManager.DAL;
using WebMatrix.WebData;
using KaryaManager.CustomWebSecurityWrapper;

namespace KaryaManager.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        //private KaryaDBContext db = new KaryaDBContext();
        private UnitOfWork unitOfWork;
        private WebSecurityWrapper webSecurity;

        public TaskController()
        {
            unitOfWork = new UnitOfWork();
            webSecurity = new WebSecurityWrapper();
        }

        public TaskController(UnitOfWork uw = null, WebSecurityWrapper wr = null)
        {
            if (uw == null)
                unitOfWork = new UnitOfWork();
            else
                unitOfWork = uw;
            if(wr == null)
                webSecurity = new WebSecurityWrapper();
            else
                this.webSecurity = wr;
        }

        //
        // GET: /Task/

        public ActionResult Index()
        {
            var tasks = unitOfWork.TaskRepository.Get();
            //var tasks = db.Tasks.Include(t => t.Project).Include(t => t.User);
            return View(tasks);
        }

        //
        // GET: /Task/Details/5

        public ActionResult Details(int id = 0)
        {
            Task task = unitOfWork.TaskRepository.GetByID(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        //
        // GET: /Task/Create

        public ActionResult Create(int id = 0)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole) || User.IsInRole(CurrentRole.memberRole)))
                return HttpNotFound();
            ViewBag.assignee = new SelectList(getUserInProject(id), "userId", "userName");
            ViewBag.task_statuses = getTaskStatuses();
            Task task = new Task();
            task.projectId = id;
            task.progress = 0;
            task.priority = 0;
            task.taskStatus = EnumExtension.GetEnumDescription(TaskStatus.Open);
           // ViewBag.assignee = new SelectList(db.Users, "userId", "userName");
            return PartialView(task);
        }

        //
        // POST: /Task/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Task task)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.TaskRepository.Insert(task);
                unitOfWork.Commit();
                //db.Tasks.Add(task);
               // db.SaveChanges();
                TempData["message"] = "Task created successfully.";
                return RedirectToAction("TaskDashboard", "Dashboard", new { id = task.projectId });
            }
            ViewBag.assignee = new SelectList(getUserInProject(task.projectId), "userId", "userName");
            ViewBag.task_statuses = getTaskStatuses();
            return PartialView(task);
        }

        //
        // GET: /Task/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole) || User.IsInRole(CurrentRole.memberRole)))
                return HttpNotFound();
            Task task = unitOfWork.TaskRepository.GetByID(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            ViewBag.assignee = new SelectList(getUserInProject(task.projectId), "userId", "userName", task.assignee);
            ViewBag.task_statuses = getTaskStatuses();
            return View(task);
        }

        //
        // POST: /Task/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Task task)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.TaskRepository.Update(task);
                unitOfWork.Commit();
                //db.Entry(task).State = EntityState.Modified;
                //db.SaveChanges();
                TempData["message"] = "Task updated successfully.";
                return RedirectToAction("TaskDashboard", "Dashboard", new { id = task.projectId });
            }
            ViewBag.assignee = new SelectList(getUserInProject(task.projectId), "userId", "userName", task.assignee);
            ViewBag.task_statuses = getTaskStatuses();
            return View(task);
        }

        public ActionResult Delete(int id)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole) || User.IsInRole(CurrentRole.memberRole)))
                return HttpNotFound();
            try
            {
                Task task = unitOfWork.TaskRepository.GetByID(id);
                int projectId = (int)task.projectId;
                unitOfWork.TaskRepository.Delete(id);
                unitOfWork.Commit();
                TempData["message"] = "Task deleted successfully.";
                return RedirectToAction("TaskDashboard", "Dashboard", new { id = projectId });
            }
            catch
            {
                TempData["error"] = "Error deleting task.";
                return null;
            }
        }

        //
        // POST: /Task/Delete/5

        //[HttpPost, ActionName("DeleteConfirmed")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Task task = unitOfWork.TaskRepository.GetByID(id);
        //    int projectId = (int)task.projectId;
        //    unitOfWork.TaskRepository.Delete(id);
        //    unitOfWork.Commit();
        //    //db.Tasks.Remove(task);
        //    //db.SaveChanges();
        //    return RedirectToAction("TaskDashboard", "Dashboard", new { id = projectId });
        //}

        [HttpPost]
        public ActionResult UpdateStatus(String status, int taskId)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole) || User.IsInRole(CurrentRole.memberRole)))
                return HttpNotFound();
            Task task = unitOfWork.TaskRepository.GetByID(taskId);
            task.taskStatus = status;
            unitOfWork.TaskRepository.Update(task);
            unitOfWork.Commit();
            return null;
        }

        [HttpPost]
        public ActionResult UpdateUser(int? assignee, int taskId)
        {
            if (!(User.IsInRole(CurrentRole.leaderRole) || User.IsInRole(CurrentRole.memberRole)))
                return HttpNotFound();
            Task task = unitOfWork.TaskRepository.GetByID(taskId);
            task.assignee = assignee;
            unitOfWork.TaskRepository.Update(task);
            unitOfWork.Commit();
            return null;
        }

        protected override void Dispose(bool disposing)
        {
            unitOfWork.Dispose();
            //db.Dispose();
            base.Dispose(disposing);
        }

        [NonAction]
        public List<User> getUserInProject(int? projectId)
        {
            if (projectId == null)
                return null;
            ICollection<Project_user> project_users = unitOfWork.ProjectRepository.GetByID(projectId).Project_user;
            List<User> users = new List<User>();
            foreach (Project_user pu in project_users)
            {
                users.Add(pu.User);
            }
            users.Add(unitOfWork.ProjectRepository.GetByID(projectId).User);
            return users;
        }

        [NonAction]
        public List<String> getTaskStatuses()
        {
            List<String> ret = new List<String>();
            foreach (TaskStatus status in Enum.GetValues(typeof(TaskStatus)))
                ret.Add(EnumExtension.GetEnumDescription(status));
            return ret;
        }
    }
}

KaryaManager/KaryaManager/KaryaManager/Views/Task/Create.cshtml
@model KaryaManager.Models.Task

@{
    ViewBag.Title = "Create";
}

@*<h2>Create</h2>*@

@using (Html.BeginForm(Html.BeginForm("Create", "Task", FormMethod.Post, new { id = "createTaskForm" })))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Task</legend>

        @Html.HiddenFor(model => model.taskId)
        @Html.HiddenFor(model => model.projectId)

        <div class="editor-label">
            @Html.LabelFor(model => model.taskName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.taskName, new { placeholder = "Name" })
            @Html.ValidationMessageFor(model => model.taskName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.taskStatus)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.taskStatus, new SelectList(ViewBag.task_statuses))
            @Html.ValidationMessageFor(model => model.taskStatus)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.taskDescription)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.taskDescription, new { placeholder = "Description" })
            @Html.ValidationMessageFor(model => model.taskDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.assignee, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.assignee, (SelectList)ViewBag.assignee, String.Empty)
            @*@Html.DropDownList("assignee", String.Empty)*@
            @Html.ValidationMessageFor(model => model.assignee)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.start_date)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.start_date, new { @class = "datepicker", Value = Model.start_date.ToString() })
            @Html.ValidationMessageFor(model => model.start_date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.estimate_hour)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.estimate_hour, new { placeholder = "e.g. 5 for 5 hours estimated" })
            @Html.ValidationMessageFor(model => model.estimate_hour)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.worked_hour)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.worked_hour, new { placeholder = "e.g. 5 for 5 hours worked" })
            @Html.ValidationMessageFor(model => model.worked_hour)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.priority)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.priority, new { placeholder = "0 - 5" })
            @Html.ValidationMessageFor(model => model.priority)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.progress)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.progress, new { placeholder = "Progress value, 0 to 100" })
            @Html.ValidationMessageFor(model => model.progress)
        </div>
        <p>
            <input type="submit" class="btn btn-primary" value="Create" />
        </p>
    </fieldset>
}
@*<div>
    @Html.ActionLink("Back", "TaskDashboard", "Dashboard", new { id = Model.projectId }, null)
</div>*@
<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({});
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KaryaManager/KaryaManager/KaryaManager/Views/Task/Delete.cshtml
@model KaryaManager.Models.Task

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Task</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.taskName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.taskName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.taskStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.taskStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.taskDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.taskDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.userName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.userName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.start_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.start_date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.estimate_hour)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.estimate_hour)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.worked_hour)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.worked_hour)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.priority)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.priority)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.progress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.progress)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Project.projectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Project.projectName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "TaskDashboard", "Dashboard", new { id = Model.projectId }, null)
    </p>
}

KaryaManager/KaryaManager/KaryaManager/Views/Task/Details.cshtml
@model KaryaManager.Models.Task

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Task</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.taskName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.taskName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.taskStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.taskStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.taskDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.taskDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.userName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.userName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.start_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.start_date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.estimate_hour)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.estimate_hour)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.worked_hour)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.worked_hour)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.priority)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.priority)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.progress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.progress)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Project.projectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Project.projectName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.taskId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KaryaManager/KaryaManager/KaryaManager/Views/Task/Edit.cshtml
@model KaryaManager.Models.Task

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Task</legend>

        @Html.HiddenFor(model => model.taskId)
        @Html.HiddenFor(model => model.projectId)

        <div class="editor-label">
            @Html.LabelFor(model => model.taskName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.taskName)
            @Html.ValidationMessageFor(model => model.taskName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.taskStatus)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.taskStatus, new SelectList(ViewBag.task_statuses))
            @Html.ValidationMessageFor(model => model.taskStatus)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.taskDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.taskDescription)
            @Html.ValidationMessageFor(model => model.taskDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.assignee, "Assignee")
        </div>
        <div class="editor-field">
            @Html.DropDownList("assignee", String.Empty)
            @Html.ValidationMessageFor(model => model.assignee)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.start_date)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.start_date, new { @class = "datepicker", Value = Model.start_date.ToString() })
            @Html.ValidationMessageFor(model => model.start_date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.estimate_hour)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.estimate_hour)
            @Html.ValidationMessageFor(model => model.estimate_hour)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.worked_hour)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.worked_hour)
            @Html.ValidationMessageFor(model => model.worked_hour)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.priority)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.priority)
            @Html.ValidationMessageFor(model => model.priority)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.progress)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.progress, new { @type = "range", min = 0, max = 100 })
            @Html.ValidationMessageFor(model => model.progress)
        </div>

        <p></p>
        <p>
            <input type="submit" class="btn btn-primary" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back", "TaskDashboard", "Dashboard", new { id = Model.projectId }, null)
</div>
<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({});
    });
    
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KaryaManager/KaryaManager/KaryaManager/Views/Task/Index.cshtml
@model IEnumerable<KaryaManager.Models.Task>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table  class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.taskName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.taskStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.taskDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.start_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estimate_hour)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.worked_hour)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.priority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.progress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project.projectName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.taskName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.taskStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.taskDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.start_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.estimate_hour)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.worked_hour)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.priority)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.progress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Project.projectName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.taskId }) |
            @Html.ActionLink("Details", "Details", new { id=item.taskId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.taskId })
        </td>
    </tr>
}

</table>