KaryaManager/KaryaManager/KaryaManager/Models/Project_user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_user
    {
        public int project_userId { get; set; }
        public int projectId { get; set; }
        public int userId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}

KaryaManager/KaryaManager/KaryaManager/Controllers/ProjectUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KaryaManager.Models;
using KaryaManager.DAL;
using WebMatrix.WebData;
using System.Web.Security;
using KaryaManager.CustomWebSecurityWrapper;

namespace KaryaManager.Controllers
{
    [Authorize]
    public class ProjectUserController : Controller
    {
        private KaryaDBContext db = new KaryaDBContext();
        private UnitOfWork unitOfWork;
        private WebSecurityWrapper webSecurity;

        public ProjectUserController()
        {
            unitOfWork = new UnitOfWork();
            webSecurity = new WebSecurityWrapper();
        }

        public ProjectUserController(UnitOfWork uw = null, WebSecurityWrapper wr = null)
        {
            if (uw == null)
                unitOfWork = new UnitOfWork();
            else
                unitOfWork = uw;
            if(wr == null)
                webSecurity = new WebSecurityWrapper();
            else
                this.webSecurity = wr;
        }

        //
        // GET: /ProjectUser/
        [ChildActionOnly]
        public ActionResult Index(int id = 0)
        {
            var project_user = unitOfWork.ProjectRepository.GetByID(id).Project_user;
            return PartialView(project_user);
        }

        //
        // GET: /ProjectUser/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    Project_user project_user = db.Project_user.Find(id);
        //    if (project_user == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project_user);
        //}

        //
        // GET: /ProjectUser/Create

        public ActionResult Create(int id = 0)
        {
            Project_user project_user = new Project_user();
            project_user.projectId = id;
            ViewBag.userId = new SelectList(getUserInContact(id), "userId", "userName");
            return PartialView(project_user);
        }

        //
        // POST: /ProjectUser/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project_user project_user)
        {
            if (ModelState.IsValid)
            {
                AddUserToTeamRole(project_user.projectId, unitOfWork.UserRepository.GetByID(project_user.userId).userName);
                unitOfWork.ProjectUserRepository.Insert(project_user);
                unitOfWork.Commit();
                //db.Project_user.Add(project_user);
                //db.SaveChanges();
                TempData["message"] = "Team member added successfully.";
                return RedirectToAction("Index", "Dashboard", new { id = project_user.projectId } );
            }
            ViewBag.userId = new SelectList(getUserInContact(project_user.projectId), "userId", "userName");
            return PartialView(project_user);
        }

        ////
        //// GET: /ProjectUser/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    Project_user project_user = unitOfWork.ProjectUserRepository.GetByID(id);
        //    if (project_user == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.userId = new SelectList(getUserInContact(project_user.projectId), "userId", "userName", project_user.userId);
        //    return View(project_user);
        //}

        ////
        //// POST: /ProjectUser/Edit/5

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(Project_user project_user)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        unitOfWork.ProjectUserRepository.Update(project_user);
        //        unitOfWork.Commit();
        //       // db.Entry(project_user).State = EntityState.Modified;
        //       // db.SaveChanges();
        //        TempData["message"] = "Team member updated successfully.";
        //        return RedirectToAction("Index", "Dashboard", project_user.projectId);
        //    }
        //    ViewBag.userId = new SelectList(getUserInContact(project_user.projectId), "userId", "userName", project_user.userId);
        //    return View(project_user);
        //}


        //
        // GET: /ProjectUser/Delete/5

        public ActionResult Delete(int id = 0)
        {
            try
            {
                Project_user project_user = unitOfWork.ProjectUserRepository.GetByID(id);
                if (project_user == null)
                {
                    return HttpNotFound();
                }
                int projectId = project_user.projectId;
                RemoveUserFromTeamRole(projectId, project_user.User.userName);
                unitOfWork.ProjectUserRepository.Delete(id);
                unitOfWork.Commit();
                TempData["message"] = "User removed successfully.";
                return RedirectToAction("Index", "Dashboard", new { id = projectId });

            }
            catch
            {
                TempData["error"] = "Error removing user.";
                return null;
            }
        }

        //
        // POST: /ProjectUser/Delete/5

        //[HttpPost, ActionName("DeleteConfirmed")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Project_user project_user = unitOfWork.ProjectUserRepository.GetByID(id);
        //    int projectId = project_user.projectId;
        //    RemoveUserFromTeamRole(projectId, project_user.User.userName);
        //    unitOfWork.ProjectUserRepository.Delete(id);
        //    unitOfWork.Commit();
        //    //db.Project_user.Remove(project_user);
        //    //db.SaveChanges();
        //    TempData["message"] = "Team member deleted successfully.";
        //    return RedirectToAction("Index", "Dashboard", new { id = projectId });
        //}

        protected override void Dispose(bool disposing)
        {
            unitOfWork.Dispose();
            base.Dispose(disposing);
        }

        [NonAction]
        public List<User> getUserInContact(int projectId)
        {
            ICollection<Contact> contacts = unitOfWork.UserRepository.GetByID(webSecurity.CurrentUserId).Contacts;
            List<User> userInProject = getUserInProject(projectId);
            List<User> users = new List<User>();
            foreach (Contact contact in contacts)
            {
                if(!userInProject.Contains(contact.User1))
                    users.Add(contact.User1);
            }
            return users;
        }

        [NonAction]
        public List<User> getUserInProject(int? projectId)
        {
            if (projectId == null)
                return null;
            ICollection<Project_user> project_users = unitOfWork.ProjectRepository.GetByID(projectId).Project_user;
            List<User> users = new List<User>();
            foreach (Project_user pu in project_users)
            {
                users.Add(pu.User);
            }
            return users;
        }

        [NonAction]
        public void AddUserToTeamRole(int projectId, String userName)
        {
            String memberRole = projectId + " Member";
            Roles.AddUserToRole(userName, memberRole);
        }

        [NonAction]
        public void RemoveUserFromTeamRole(int projectId, String userName)
        {
            String memberRole = projectId + " Member";
            Roles.RemoveUserFromRole(userName, memberRole);
        }
    }
}

KaryaManager/KaryaManager/KaryaManager/Views/ProjectUser/Create.cshtml
@model KaryaManager.Models.Project_user

@{
    ViewBag.Title = "Create";
}

@*<h2>Create</h2>*@

@using (Html.BeginForm("Create", "ProjectUser", FormMethod.Post, new { id = "createProjectUserForm"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Team Member</legend>
        @Html.HiddenFor(model => model.projectId)
        <div class="editor-label">
            @Html.LabelFor(model => model.userId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.userId, (SelectList)ViewBag.userId, String.Empty)
            @*@Html.DropDownList("userId", String.Empty)*@
            @Html.ValidationMessageFor(model => model.userId)
        </div>

        <p>
            <input type="submit" class="btn btn-primary" value="Add" />
        </p>
    </fieldset>
}

@*<div>
    @Html.ActionLink("Back", "Index", "Dashboard", new { id = Model.projectId }, null)
</div>*@

KaryaManager/KaryaManager/KaryaManager/Views/ProjectUser/Delete.cshtml
@model KaryaManager.Models.Project_user

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Project_user</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Project.projectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Project.projectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.userName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.userName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

KaryaManager/KaryaManager/KaryaManager/Views/ProjectUser/Details.cshtml
@model KaryaManager.Models.Project_user

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Project_user</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Project.projectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Project.projectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.userName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.userName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.project_userId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KaryaManager/KaryaManager/KaryaManager/Views/ProjectUser/Edit.cshtml
@model KaryaManager.Models.Project_user

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project_user</legend>

        @Html.HiddenFor(model => model.project_userId)

        <div class="editor-label">
            @Html.LabelFor(model => model.projectId, "Project")
        </div>
        <div class="editor-field">
            @Html.DropDownList("projectId", String.Empty)
            @Html.ValidationMessageFor(model => model.projectId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.userId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("userId", String.Empty)
            @Html.ValidationMessageFor(model => model.userId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KaryaManager/KaryaManager/KaryaManager/Views/ProjectUser/Index.cshtml
@model IEnumerable<KaryaManager.Models.Project_user>

@{
    ViewBag.Title = "Index";
}

<h2>Team members</h2>

<table  class="table table-striped">
    <tr>
        <th>
            User Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            <a href="#" OnClick="deleteTask(@item.project_userId);" >Delete</a>
        </td>
    </tr>
}

</table>
<div id="deleteModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Remove user</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to remove this user from the team?</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    <button class="btn btn-primary" id="btnDeleteUser">Confirm</button>
  </div>
</div>
<script>
    $(document).ready()
    {
        var deleteLinkObj;
        function deleteTask(id) {
            deleteLinkObj = id;
            $("#deleteModal").modal('show');
        }
        $("#btnDeleteUser").click(function () {
            deleteLinkObj
            $("#deleteModal").modal("hide");
            var href = '@Url.Action("Delete", "ProjectUser", new { id = "_Id" })'.replace("_Id", deleteLinkObj);
            location.href = href;
        });
    }
</script>